# test_kanlayer.jl — Phase 4: KANLayer forward, gradient, state, and edge cases

include("test_infra.jl")

function _kanlayer_fd_maxdiff(key::Symbol, layer, x, ps, st; ϵ=1e-5)
    g_ad = getfield(Zygote.gradient(p -> sum(layer(x, p, st)[1]), ps)[1], key)
    p = getfield(ps, key)
    p_flat = vec(copy(p))
    g_flat = similar(p_flat)

    for i in eachindex(p_flat)
        f_vals = zeros(4)
        for (idx, h) in enumerate((2ϵ, ϵ, -ϵ, -2ϵ))
            p_flat[i] = p_flat[i] + h
            p_new = reshape(p_flat, size(p))
            ps_new = merge(ps, NamedTuple{(key,)}((p_new,)))
            f_vals[idx] = sum(layer(x, ps_new, st)[1])
            p_flat[i] = p_flat[i] - h
        end
        g_flat[i] = (-f_vals[1] + 8f_vals[2] - 8f_vals[3] + f_vals[4]) / (12ϵ)
    end

    return maximum(abs.(g_ad .- reshape(g_flat, size(g_ad))))
end

@testset "KANLayer (Phase 4)" begin
    IN_DIM = 2
    OUT_DIM = 3
    NUM = 5
    K = 3
    BATCH = 100

    # Reference data and parameters generated by PyKAN.
    x_ref = load_reference("kanlayer_input")            # (100, 2)
    y_ref = load_reference("kanlayer_output")           # (100, 3)
    ps_ref = (
        coef=load_reference("kanlayer_coef"),
        scale_base=load_reference("kanlayer_scale_base"),
        scale_sp=load_reference("kanlayer_scale_sp"),
    )
    st_ref = (
        grid=load_reference("kanlayer_grid"),
        mask=load_reference("kanlayer_mask"),
    )
    layer_ref = KANLayer(IN_DIM, OUT_DIM, NUM, K)

    @testset "A) forward values" begin
        @testset "A1: output shape" begin
            y = layer_ref(x_ref, ps_ref, st_ref)[1]
            @test size(y) == (BATCH, OUT_DIM)
        end

        @testset "A2: forward vs PyKAN" begin
            y = layer_ref(x_ref, ps_ref, st_ref)[1]
            @test maximum(abs.(y .- y_ref)) < 1e-6
        end

        @testset "A3: Lux.setup" begin
            layer = KANLayer(3, 5, 5, 3)
            ps, st = Lux.setup(rng, layer)
            @test ps isa NamedTuple && st isa NamedTuple
        end

        @testset "A4: type stability" begin
            @test begin
                @inferred layer_ref(x_ref, ps_ref, st_ref)
                true
            end
        end
    end

    layer = KANLayer(3, 5, 5, 3)
    ps, st = Lux.setup(rng, layer)
    x = randn(rng, 100, 3)

    @testset "B) gradient paths" begin
        @testset "B1: coef non-zero" begin
            g = getfield(Zygote.gradient(p -> sum(layer(x, p, st)[1]), ps)[1], :coef)
            @test !all(iszero, g) && !any(isnan, g)
        end

        @testset "B2: scale_sp non-zero" begin
            g = getfield(Zygote.gradient(p -> sum(layer(x, p, st)[1]), ps)[1], :scale_sp)
            @test !all(iszero, g) && !any(isnan, g)
        end

        @testset "B3: scale_base non-zero" begin
            g = getfield(Zygote.gradient(p -> sum(layer(x, p, st)[1]), ps)[1], :scale_base)
            @test !all(iszero, g) && !any(isnan, g)
        end

        @testset "B4: grid zero gradient" begin
            grads = Zygote.gradient(p -> sum(layer(x, p, st)[1]), ps)[1]
            @test !(:grid in propertynames(grads))
        end

        @testset "B5: mask zero gradient" begin
            grads = Zygote.gradient(p -> sum(layer(x, p, st)[1]), ps)[1]
            @test !(:mask in propertynames(grads))
        end

        @testset "B6: coef vs FD" begin
            @test _kanlayer_fd_maxdiff(:coef, layer, x, ps, st) < 1e-4
        end

        @testset "B7: scale_sp vs FD" begin
            @test _kanlayer_fd_maxdiff(:scale_sp, layer, x, ps, st) < 1e-4
        end

        @testset "B8: scale_base vs FD" begin
            @test _kanlayer_fd_maxdiff(:scale_base, layer, x, ps, st) < 1e-4
        end
    end

    @testset "C) state transfer" begin
        @testset "C1: same keys" begin
            _, st2 = layer(x, ps, st)
            @test sort(collect(propertynames(st2))) == sort(collect(propertynames(st)))
        end

        @testset "C2: grid unchanged" begin
            _, st2 = layer(x, ps, st)
            @test st2.grid == st.grid
        end

        @testset "C3: mask unchanged" begin
            _, st2 = layer(x, ps, st)
            @test st2.mask == st.mask
        end

        @testset "C4: state fields are arrays" begin
            @test all(v -> v isa AbstractArray, values(st))
        end
    end

    @testset "D) edge cases" begin
        @testset "D1: all-zero mask" begin
            st_zero = merge(st, (mask=zeros(3, 5),))
            y = layer(x, ps, st_zero)[1]
            @test all(iszero, y) && !any(isnan, y)
        end

        @testset "D2: single-edge mask" begin
            mask1 = zeros(3, 5)
            mask1[1, 1] = 1.0
            st1 = merge(st, (mask=mask1,))
            y = layer(x, ps, st1)[1]
            @test all(iszero, y[:, 2:5]) && !all(iszero, y[:, 1])
        end

        @testset "D3: extreme large input" begin
            x_big = (rand(rng, 16, 3) .- 0.5) .* 200.0
            y = layer(x_big, ps, st)[1]
            @test all(isfinite, y)
        end

        @testset "D4: sp_trainable=false" begin
            layer_fixed = KANLayer(3, 5, 5, 3; sp_trainable=false)
            ps_f, st_f = Lux.setup(rng, layer_fixed)
            grads = Zygote.gradient(p -> sum(layer_fixed(x, p, st_f)[1]), ps_f)[1]
            @test !all(iszero, getfield(grads, :coef)) &&
                  !(:scale_sp in propertynames(grads))
        end

        @testset "D5: sb_trainable=false" begin
            layer_fixed = KANLayer(3, 5, 5, 3; sb_trainable=false)
            ps_f, st_f = Lux.setup(rng, layer_fixed)
            grads = Zygote.gradient(p -> sum(layer_fixed(x, p, st_f)[1]), ps_f)[1]
            @test !all(iszero, getfield(grads, :coef)) &&
                  !(:scale_base in propertynames(grads))
        end

        @testset "D6: batch=1" begin
            y = layer(randn(rng, 1, 3), ps, st)[1]
            @test size(y) == (1, 5)
        end

        @testset "D7: k=1 linear spline" begin
            layer_k1 = KANLayer(3, 5, 5, 1)
            ps_k1, st_k1 = Lux.setup(rng, layer_k1)
            y = layer_k1(randn(rng, 16, 3), ps_k1, st_k1)[1]
            @test size(y) == (16, 5) && !any(isnan, y)
        end
    end
end
